### PR TITLE
Use ES2017 lib (for Object.getOwnPropertyDescriptors)

### PR DESCRIPTION
**Pull request by zoontek**

### CODE REVIEW

**Comment by bloodyowl** [comment]
What does this change solves?

**Comment by zoontek** [comment]
`Object.getOwnPropertyDescriptors` is a feature from [ES2017](https://flaviocopes.com/es2017/) and included in `es2017.object` TS lib. This could raise warnings with some toolings.

**Comment by bloodyowl** [comment]
Yeah I know what it does, but my question is more: how does our TS Config impact users on that?

**Comment by zoontek** [comment]
For users there is no impact, it fixes a warning for boxed maintainers / folks who fork it.

**Pull request merged**
